# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  rplsinfo_config = debug

else ifeq ($(config),release)
  rplsinfo_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := rplsinfo

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

rplsinfo:
ifneq (,$(rplsinfo_config))
	@echo "==== Building rplsinfo ($(rplsinfo_config)) ===="
	@${MAKE} --no-print-directory -C . -f rplsinfo.make config=$(rplsinfo_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f rplsinfo.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   rplsinfo"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"
